name: CI with R, Python, and Pages Deployment

on: 
  push:
    branches: [ master ]
  repository_dispatch:
    types: [rebuild]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install R
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
    - name: Get R library path
      id: get-r-lib-path
      run: |
         echo "R_LIBS_USER=${{ github.workspace }}/R/library" >> $GITHUB_ENV
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: r-
    - name: Install R packages
      run: |
         mkdir -p ${{ env.R_LIBS_USER }}
         Rscript -e "install.packages(c('stringr', 'dplyr', 'tidyr', 'writexl', 'VennDiagram', 'ggplot2', 'jsonlite', 'readr'), repos='https://cran.rstudio.com/', lib='${{ env.R_LIBS_USER }}')"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python packages
      run: |
        pip install pandas jinja2 natsort
    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick
    - name: Run Analysis
      run: ./runAnalysis.sh
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/ # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          single-commit: true
